### ISSUE TITLE
The frequent use of append with small sizes can consume excessive memory

### ISSUE THREAD

**Issue by Chillax-0v0** [AutoMQ/automq-for-rocketmq#855]
When we set `enable.auto.commit=false` and commit consumer offsets manually during tail read, many append requests will be sent to streams. 
This will result in the allocation of many small objects in memory, and they will have a long lifespan (only being reclaimed after they are uploaded to S3).

The following image illustrates the memory allocation status of a broker which holds all partitions (50 in total) of the topic "__consumer_offsets".
![image](https://github.com/AutoMQ/automq-for-rocketmq/assets/78631860/1e316136-39b4-4fbc-b30e-10bd47c90d89)
We can see that there are a considerable number of 'StreamRecordBatch' objects. In reality, the amount of data they actually store is quite small.

Possible solution: When batching uploads to S3, consider not only the total size of the data but also the number of `StreamRecordBatch` objects.

**Comment by LetLetMe** [comment]
Gorgeous！

**Comment by Chillax-0v0** [comment]
solve https://github.com/AutoMQ/automq-for-kafka/issues/608

**Comment by Chillax-0v0** [comment]
part of https://github.com/AutoMQ/automq-for-kafka/issues/621

**Comment by superhx** [comment]
fixed in https://github.com/AutoMQ/automq-for-rocketmq/pull/907
